### PR TITLE
EC1.x user guide

### LINKED ISSUE #170: - User Guide Needed
As a new EC user, I would like to understand how to deploy and to use EC connectivity as-a-service, so that it would apply in my business use case.

### PR DESCRIPTION
**Pull request by ramaraosrikakulapu**
EC1.x user guide

### CODE REVIEW

**Comment by palokam** [comment]
First of overall document seems to be better suited for Architect and Developer persona than user guide

**Description:** What is the problem is solving we are solving - less technical is better

**When do you use this product:** Some use cases and scenarios

**Architecture** need to be very simple: Remove any cloud specific jargon in the picture

**How do they Engage to use the product:**

**How to check the health of the connection**

**FAQs**

**Comment by palokam** [comment]
- Agent Operations and flags are useful for the users
- Adding few lines about Multi layer Security will be required

**Comment by ramaraosrikakulapu** [comment]
**12/06/2021:**
**Attendees**: Rama chandra, Saurabh, Akhil, Sukesh and Puja
**MoM**:
- Gone through the initial draft version
- Table of Contents is good
- Requested following changes - 
  - Introduction to EC - Highlight the EC features in the starting and platform details can be followed
  - What is EC - EC is a connectivity tool to establish connectivity b/w any 2 network. Not just 'Predix Cloud' and 'enterprise resources'
  - Characteristics - 'Is a system that contains many smaller software systems (self-contained microservice)' - have to confirm with @ayasuda-ge 
  - 'Cloud Foundry Marketplace' - Change the heading name related to EC 
  - 'Components of EC' -  EC service, Agent (types - gateway, server, client, gw:client, gw:server) and Plugin types
  - Most of the times Oracle DB mentioned as target system. Requested to give generic information instead of specific type of DB
- Shared the [wiki](https://github.com/EC-Release/sdk/wiki) link to get more details about product. Team was following GE digital doc for user guide
- Shared the 'EC first glance' to Rama chandra after the meeting
- Ram (EC) have to come up with table of contents for 'Developer Guide'

**Comment by ramaraosrikakulapu** [comment]
**12/08/2021:**
**Attendees**: Rama chandra, Sukesh, Puja, Apolo and Ram (EC)
**MoM**:

- Document the content in .md file for better collaboration
- Put the user guide in [userguide.md](https://github.com/ramaraosrikakulapu/sdk/blob/v1/userguide.md) 
- Prepare 'Table of Contents' for [developer guide](https://github.com/ramaraosrikakulapu/sdk/blob/v1/developerguide.md)

**Review by ayasuda-ge — APPROVED** [review]

**Pull request merged**
